name: project2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mpi4py/setup-mpi@v1
    - uses: snickerbockers/submodules-init@v4
            

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build
    
    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: Install Singularity dependencies
      uses: eWaterCycle/setup-singularity@v7

    - name: Run a singularity container
      run: singularity run docker://alpine cat /etc/os-release
